spring:
  application:
    name: blog-service
  redis:
    url: redis://51.250.77.123:6379
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/maxima/protocol/openid-connect/certs

server:
  port: 0
  error:
    include-stacktrace: never

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/
    healthcheck:
      enabled: true

user-service:
  endpoint: http://user-service/user